name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build_aar:
    name: Build AAR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: Gradle build
        run: nix develop --command ./gradlew build

      - name: Rename AAR to opus.aar
        run: cp opus/build/outputs/aar/opus-release.aar opus.aar

      - name: Upload AAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opus.aar
          path: opus.aar

  publish_release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build_aar
    if: github.ref_type == 'tag'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: opus.aar
          path: .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: opus.aar
